spring.application.name=app

# Configuração da URL e Driver do H2
spring.datasource.url=jdbc:h2:mem:caadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilita o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Set the URL path (default is /h2-console)
spring.h2.console.path=/h2-console

# Faz o Hibernate criar automaticamente as tabelas a partir das suas entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

